version: '3.7'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: loan
      POSTGRES_PASSWORD: loan
      POSTGRES_DB: loan
    volumes:
      - dbdata:/var/lib/postgresql/data/
  loan-adminer:
    image: adminer
    ports:
      - 18080:8080
volumes:
  dbdata:
    driver: local